# Generated by Django 3.1.5 on 2021-01-11 15:16

# Ao executar makemigrations, você está dizendo ao Django que você fez algumas
#  mudanças em seus modelos (neste caso, você fez novas modificações) e que 
# você gostaria que as alterações sejam armazenadas como uma migração.

"""
As migrações são como o Django armazena as alterações nos seus modelos 
(e, portanto, seu esquema de banco de dados) - eles são apenas arquivos no disco. 
Você pode ler a migração para seu novo modelo, se quiser; é o arquivo 
polls/migrations/0001_initial.py. Não se preocupe, você não precisa lê-los cada 
vez que o Django cria um, mas eles são projetados para serem editados no caso de 
você precisar ajustar manualmente como Django muda as coisas.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
